version: '3.8'
services:
  alert_service:
    build: ./alert_service
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/MonitoramentoLogins/logs/alert_service:/app/logs
    ports:
      - "5002:5002"
    env_file:
      - .env
    restart: always

  ixcsoft_service:
    build: ./ixcsoft_service
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/MonitoramentoLogins/logs/ixcsoft_service:/app/logs
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: always

  monitor_service:
    build: ./monitor_service
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/MonitoramentoLogins/logs/monitor_service:/app/logs
    depends_on:
      - ixcsoft_service
      - alert_service
      - olt_service
    env_file:
      - .env
    restart: always

  olt_service:
    build: ./olt_service
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/MonitoramentoLogins/logs/olt_service:/app/logs
    ports:
      - "5003:5003"
    env_file:
      - .env
    restart: always

  telegram_bot:
    build: ./telegram_bot
    restart: always
    volumes:
      - /opt/MonitoramentoLogins/logs/telegram_bot:/app/logs
    env_file:
      - .env

